apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  namespace: pipeline
spec:
  storageClassName: docker-registry-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/d/data/docker-registry/
