apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: pipeline
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host_mnt/d/data/jenkins/
