apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-svc
  namespace: pipeline
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
  ports:
    - name: jenkins-http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: jenkins-https
      port: 443
      protocol: TCP
      targetPort: 8080
